name: deploy
on: push
jobs:
  build_deploy:
    name: Build sapper app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build Sapper
        uses: truewebartisans/actions-sapper@master
        with:
          args: "--legacy --basepath sapper-gh-pages-gh-actions"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: __sapper__/export/sapper-gh-pages-gh-actions
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
